---
collections:
  - community.general

galaxy_info:
  author: Sirn Thanabulpong
  description: Install and supervise HAProxy.
  license: BSD-3-Clause
  min_ansible_version: 2.15.0
  platforms:
    - name: FreeBSD
      versions:
        - all

allow_duplicates: true
