---
nginx_exporter_user: nobody

nginx_exporter_listen_address: 127.0.0.1:9113

nginx_exporter_logger: |
  #!/usr/local/bin/execlineb -P
  s6-log -b n10 s1000000 t !"gzip -nq9" /var/log/nginx-exporter/

nginx_exporter_scrape_uri: http://127.0.0.1:8181/stub_status

# S6 supervision is disabled by default. Enable it to supervise this service.
s6: false
