---
blackbox_exporter_user: prometheus

blackbox_exporter_listen_address: 127.0.0.1:9115

blackbox_exporter_logger: |
  #!/usr/local/bin/execlineb -P
  s6-log -b n10 s1000000 t !"gzip -nq9" /var/log/blackbox_exporter/

blackbox_exporter_modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      method: GET
      tls_config:
        insecure_skip_verify: false

# S6 supervision is disabled by default. Enable it to supervise this service.
s6: false
