---
- name: reboot system
  become: true
  ansible.builtin.shell: sleep 2 && shutdown -r now "Maintenance reboot"
  async: 0
  poll: 0
  register: reboot_system
  ignore_errors: true
  changed_when: reboot_system is succeeded
  failed_when: reboot_system is not succeeded

- name: wait for system reboot
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 600
  register: wait_for_system_reboot
  changed_when: wait_for_system_reboot is succeeded
  failed_when: wait_for_system_reboot is not succeeded

- name: reload racct
  become: true
  ansible.builtin.shell: |
    rctl -r ":"
    {% for rule in racct_rules %}
    rctl -a "{{ rule }}"
    {% endfor %}
  register: reload_racct
  ignore_errors: true
  changed_when: reload_racct is succeeded
  failed_when: reload_racct is not succeeded
