---
- name: flush pf
  become: true
  ansible.builtin.command: pfctl -F all -f /etc/pf.conf
  async: 0
  poll: 0
  register: flush_pf
  changed_when: flush_pf is succeeded
  failed_when: flush_pf is not succeeded

- name: wait for pf flush
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 600
  register: wait_for_pf_flush
  changed_when: false
