---
redis_addresses:
  - 127.0.0.1

redis_databases: 16

redis_logger: |
  #!/usr/local/bin/execlineb -P
  s6-log -b n10 s1000000 t !"gzip -nq9" /var/log/redis/

redis_max_memory:

redis_max_memory_policy:

redis_port: 6379

redis_requirepass:

redis_snapshotting:
  - { after: 900, changes: 1 }
  - { after: 300, changes: 10 }
  - { after: 60, changes: 10000 }

redis_snapshot_filename: dump.rdb

redis_snapshot_dir: /var/db/redis

redis_tls: false

redis_tls_auth: false

redis_tls_auth_cacert_file:

redis_tls_cert_file:

redis_tls_key_file:

redis_tls_port: 0

redis_unix_socket:

redis_unix_socket_perm: 777


# S6 supervision is disabled by default. Enable it to supervise this service.
s6: false
