---
openntpd_constraints:
  - https://www.cloudflare.com/
  - https://www.google.com/

openntpd_force_sync: false

openntpd_logger: |
  #!/usr/local/bin/execlineb -P
  s6-log -b n10 s1000000 t !"gzip -nq9" /var/log/openntpd/

openntpd_servers:
  - pool.ntp.org


# S6 supervision is disabled by default. Enable it to supervise this service.
s6: false
