---
name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linting tools
        run: |
          pip install "ansible-core>2.14,<2.17"
          pip install "ansible-lint==24.*" "yamllint"
      - name: Yamllint
        run: yamllint galaxy.yml meta/ roles/ .yamllint.yml
      - name: Ansible lint
        run: ansible-lint
